language: go
go:
  - 1.8.3
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -v -service=travis-ci
after_success:
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash